# Generated by Django 5.2.6 on 2025-09-25 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks_api.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tasks_api.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('calendar', 'Calendar'), ('inbox', 'Inbox'), ('today', 'Today'), ('upcoming', 'Upcoming'), ('project', 'Project')], max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_views', to='tasks_api.section')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('totally_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='medium', max_length=9)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveIntegerField(default=15, help_text='Duration in minutes')),
                ('repeat', models.CharField(blank=True, choices=[('every day', 'Every Day'), ('every week', 'Every Week'), ('every month', 'Every Month'), ('every year', 'Every Year')], help_text='Repeat pattern for the task', max_length=12, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('calendar', 'Calendar'), ('inbox', 'Inbox'), ('today', 'Today'), ('upcoming', 'Upcoming'), ('project', 'Project')], max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_views', to='tasks_api.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['parent'], name='tasks_api_p_parent__e7860f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='tasks_api_p_name_f4eba6_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['project'], name='tasks_api_s_project_be3236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='sectionview',
            index=models.Index(fields=['view'], name='tasks_api_s_view_89495e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionview',
            unique_together={('section', 'view')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='tasks_api_t_project_9b691f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['section'], name='tasks_api_t_section_c63a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_api_t_due_dat_745c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed'], name='tasks_api_t_complet_f9a9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_api_t_priorit_9d3451_idx'),
        ),
        migrations.AddIndex(
            model_name='taskview',
            index=models.Index(fields=['view'], name='tasks_api_t_view_55e003_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskview',
            unique_together={('task', 'view')},
        ),
    ]
