# Generated by Django 4.2.15 on 2026-01-22 18:47

from django.db import migrations, models
import django.db.models.deletion
import tasks_api.models.project
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('theme', models.CharField(default='light', max_length=20)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('access_id', models.CharField(default=tasks_api.models.project.generate_access_id, help_text='Unique shareable code for joining the project', max_length=8, unique=True)),
                ('is_collaborative', models.BooleanField(default=False, help_text='Whether the project is in collaboration mode')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks_api.project')),
                ('user', models.ForeignKey(blank=True, help_text='The owner of the project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tasks_api.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tasks_api.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tasks_api.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('totally_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='medium', max_length=9)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveIntegerField(default=15, help_text='Duration in minutes')),
                ('repeat', models.CharField(blank=True, choices=[('every day', 'Every Day'), ('every week', 'Every Week'), ('every month', 'Every Month'), ('every year', 'Every Year')], help_text='Repeat pattern for the task', max_length=12, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Users assigned to this task (for collaborative projects)', related_name='assigned_tasks', to='tasks_api.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(help_text='User identifier')),
                ('achievement_id', models.CharField(help_text='Unique achievement identifier', max_length=100)),
                ('name', models.CharField(help_text='Achievement display name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user_id'], name='tasks_api_u_user_id_18e7e2_idx'), models.Index(fields=['achievement_id'], name='tasks_api_u_achieve_b1a7bf_idx')],
                'unique_together': {('user_id', 'achievement_id')},
            },
        ),
        migrations.CreateModel(
            name='TaskView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('calendar', 'Calendar'), ('inbox', 'Inbox'), ('today', 'Today'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('project', 'Project')], max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_views', to='tasks_api.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee_email', models.EmailField(blank=True, help_text='Email for inviting non-registered users', max_length=254, null=True)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('admin', 'Full Admin')], default='view', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message from the inviter', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the invitation expires', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the invitee responded to the invitation', null=True)),
                ('invited_by', models.ForeignKey(help_text='The user who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='tasks_api.account')),
                ('invitee', models.ForeignKey(help_text='The user who received the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='tasks_api.account')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tasks_api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('admin', 'Full Admin')], default='view', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('collaborator', models.ForeignKey(help_text='The user who has access to the task', on_delete=django.db.models.deletion.CASCADE, related_name='task_collaborations', to='tasks_api.account')),
                ('owner', models.ForeignKey(help_text='The user who owns/shared the task', on_delete=django.db.models.deletion.CASCADE, related_name='owned_collaborations', to='tasks_api.account')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='tasks_api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('calendar', 'Calendar'), ('inbox', 'Inbox'), ('today', 'Today'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('project', 'Project')], max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_views', to='tasks_api.section')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee_email', models.EmailField(blank=True, help_text='Email for inviting non-registered users', max_length=254, null=True)),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('collaborator', 'Collaborator')], default='collaborator', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message from the inviter', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the invitation expires', null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(help_text='The user who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_project_invitations', to='tasks_api.account')),
                ('invitee', models.ForeignKey(blank=True, help_text='The user who received the invitation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_project_invitations', to='tasks_api.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tasks_api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('collaborator', 'Collaborator')], default='collaborator', help_text='Role determines permissions within the project', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('collaborator', models.ForeignKey(help_text='The user who has access to the project', on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborations', to='tasks_api.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='tasks_api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='tasks_api_a_usernam_300969_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='tasks_api_a_email_3f1b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='tasks_api_a_is_acti_760630_idx'),
        ),
        migrations.AddIndex(
            model_name='taskview',
            index=models.Index(fields=['view'], name='tasks_api_t_view_55e003_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskview',
            unique_together={('task', 'view')},
        ),
        migrations.AddIndex(
            model_name='taskinvitation',
            index=models.Index(fields=['task'], name='tasks_api_t_task_id_c93488_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinvitation',
            index=models.Index(fields=['invited_by'], name='tasks_api_t_invited_b28188_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinvitation',
            index=models.Index(fields=['invitee'], name='tasks_api_t_invitee_dd3fae_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinvitation',
            index=models.Index(fields=['status'], name='tasks_api_t_status_e048e5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinvitation',
            index=models.Index(fields=['invitee_email'], name='tasks_api_t_invitee_2c4c16_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcollaboration',
            index=models.Index(fields=['task'], name='tasks_api_t_task_id_87378b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcollaboration',
            index=models.Index(fields=['owner'], name='tasks_api_t_owner_i_a89019_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcollaboration',
            index=models.Index(fields=['collaborator'], name='tasks_api_t_collabo_5ba042_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcollaboration',
            index=models.Index(fields=['is_active'], name='tasks_api_t_is_acti_1bebfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcollaboration',
            unique_together={('task', 'collaborator')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='tasks_api_t_user_id_c1cc04_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='tasks_api_t_project_9b691f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['section'], name='tasks_api_t_section_c63a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_api_t_due_dat_745c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed'], name='tasks_api_t_complet_f9a9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_api_t_priorit_9d3451_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionview',
            index=models.Index(fields=['view'], name='tasks_api_s_view_89495e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionview',
            unique_together={('section', 'view')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['user'], name='tasks_api_s_user_id_1b5489_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['project'], name='tasks_api_s_project_be3236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project'], name='tasks_api_p_project_88d162_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invited_by'], name='tasks_api_p_invited_cc0ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invitee'], name='tasks_api_p_invitee_15c190_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['status'], name='tasks_api_p_status_6c6c32_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['project'], name='tasks_api_p_project_300c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['collaborator'], name='tasks_api_p_collabo_13ada9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['role'], name='tasks_api_p_role_286e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['is_active'], name='tasks_api_p_is_acti_ce5810_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcollaboration',
            unique_together={('project', 'collaborator')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='tasks_api_p_user_id_3eebb3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['parent'], name='tasks_api_p_parent__e7860f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='tasks_api_p_name_f4eba6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['access_id'], name='tasks_api_p_access__f32d8f_idx'),
        ),
    ]
